version: '3.7'

services:
  traefik:
    image: traefik:v2.5
    container_name: traefik
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/traefik/config:/etc/traefik
    networks:
      - proxy_aug07

networks:
    proxy_aug07:
      driver: bridge
      name: proxy_aug07
