version: '3'

services:
# ...   
  box1:     
    image: containous/whoami
    container_name: box1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"
    command: --port 9077
    restart: on-failure
    networks:
      - proxy_aug07

  box2:     
    image: containous/whoami
    container_name: box2
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"
    command: --port 9088
    restart: on-failure
    networks:
      - proxy_aug07


  hello_world:
    build:
      context: hello-world
      dockerfile: Dockerfile
    image: phaustin/hello_world:aug20
    labels:
      - "traefik.enable=false"
    container_name: hello_world
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy_aug07
    working_dir: /home/jovyan/dashdir
    command: gunicorn --workers=5 --threads=1 -b 0.0.0.0:8050 app:server
    #command: python app.py


  hydro:
    build:
      context: hydro-ucflow
      dockerfile: Dockerfile
    image: phaustin/hydro:aug20
    labels:
      - "traefik.enable=false"
    container_name: hydro
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy_aug07
    working_dir: /home/jovyan/dashdir
    command: gunicorn --workers=5 --threads=1 -b 0.0.0.0:8050 app:server
    #command: python app.py


  ocgy:
    build:
      context: ocgy-dataviewer
      dockerfile: Dockerfile
    image: phaustin/ocgy:aug20
    labels:
      - "traefik.enable=false"
    container_name: ocgy
    ports:
      - "8050:8050"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - proxy_aug07
    working_dir: /home/jovyan/dashdir
    command: gunicorn --workers=5 --threads=1 -b 0.0.0.0:8050 app:server
    #command: python app.py

networks:
    proxy_aug07:
      driver: bridge
      name: proxy_aug07


