[backends]
    [backends.backend1]
      [backends.backend1.servers.server1]
      url = "http://drawdown:8050"

    [backends.backend2]
      [backends.backend2.servers.server1]
      url = "http://store:8050"

    [backends.backend3]
      [backends.backend3.servers.server1]
      url = "http://hello_world:8050"

    [backends.backend4]
      [backends.backend4.servers.server1]
      url = "http://hydro:8050"


[frontends]
    [frontends.frontend1]
      backend = "backend1"
      [frontends.frontend1.routes.test_1]
      rule = "Host: dashboard.eoastest2.xyz;PathPrefixStrip:/drawdown"
    [frontends.frontend2]
      backend = "backend2"
      [frontends.frontend2.routes.test_1]
      rule = "Host: dashboard.eoastest2.xyz;PathPrefixStrip:/store"
    [frontends.frontend3]
      backend = "backend3"
      [frontends.frontend3.routes.test_1]
      rule = "Host: dashboard.eoastest2.xyz;PathPrefixStrip:/hello"
    [frontends.frontend4]
      backend = "backend4"
      [frontends.frontend4.routes.test_1]
      rule = "Host: dashboard.eoastest2.xyz;PathPrefixStrip:/hydro"

